# Generated by Django 4.2.30 on 2026-04-19 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ManualState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_driver', models.CharField(default='', max_length=100)),
                ('kart_rating', models.CharField(choices=[('GOOD', 'Good'), ('MEDIUM', 'Medium'), ('BAD', 'Bad'), ('AUTO', 'Auto')], default='AUTO', max_length=10)),
                ('box_clear', models.BooleanField(default=True)),
                ('stint_started_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Manual State',
            },
        ),
        migrations.CreateModel(
            name='RaceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(default='APX GP', max_length=100)),
                ('apex_url', models.URLField(default='https://live.apex-timing.com/kartalcanede/')),
                ('mode', models.CharField(choices=[('LIVE', 'Live Apex'), ('MANUAL', 'Manual CSV')], default='LIVE', max_length=10)),
                ('race_duration_minutes', models.IntegerField(default=780)),
                ('mandatory_pits', models.IntegerField(default=23)),
                ('max_stint_minutes', models.IntegerField(default=45)),
                ('pit_duration_minutes', models.IntegerField(default=3)),
                ('no_pit_last_minutes', models.IntegerField(default=5)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Race Session',
            },
        ),
        migrations.CreateModel(
            name='StrategySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('HOLD', 'Hold'), ('PREPARE', 'Prepare'), ('BOX', 'Box'), ('ATTACK', 'Attack'), ('CRITICAL', 'Critical')], default='HOLD', max_length=10)),
                ('box_window', models.CharField(default='WAIT', max_length=30)),
                ('undercut', models.CharField(default='NO', max_length=20)),
                ('recommended_driver', models.CharField(default='—', max_length=100)),
                ('risk', models.CharField(default='LOW', max_length=10)),
                ('stint_elapsed_minutes', models.FloatField(default=0)),
                ('stint_remaining_minutes', models.FloatField(default=45)),
                ('race_elapsed_minutes', models.FloatField(default=0)),
                ('race_remaining_minutes', models.FloatField(default=780)),
                ('expected_pits', models.FloatField(default=0)),
                ('actual_pits', models.IntegerField(default=0)),
                ('pit_plan_status', models.CharField(default='ON PLAN', max_length=15)),
                ('pace_drop_seconds', models.FloatField(default=0)),
                ('avg3_seconds', models.FloatField(blank=True, null=True)),
                ('avg5_seconds', models.FloatField(blank=True, null=True)),
                ('kart_rating', models.CharField(default='GOOD', max_length=10)),
                ('commands', models.JSONField(default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Strategy Snapshot',
            },
        ),
        migrations.CreateModel(
            name='TeamSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kart_number', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('position', models.IntegerField(default=0)),
                ('last_lap_seconds', models.FloatField(blank=True, null=True)),
                ('best_lap_seconds', models.FloatField(blank=True, null=True)),
                ('lap_count', models.IntegerField(default=0)),
                ('pit_count', models.IntegerField(default=0)),
                ('gap', models.CharField(default='', max_length=20)),
                ('interval', models.CharField(default='', max_length=20)),
                ('is_our_team', models.BooleanField(default=False)),
                ('on_track_time', models.CharField(default='', max_length=20)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='timing.racesession')),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('session', 'kart_number')},
            },
        ),
        migrations.CreateModel(
            name='RaceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('level', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical')], default='INFO', max_length=10)),
                ('category', models.CharField(choices=[('TIMING', 'Timing'), ('STRATEGY', 'Strategy'), ('MANUAL', 'Manual'), ('SYSTEM', 'System')], default='SYSTEM', max_length=10)),
                ('message', models.TextField()),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='timing.racesession')),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='PitEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('IN', 'Pit In'), ('OUT', 'Pit Out')], max_length=3)),
                ('lap_number', models.IntegerField(blank=True, null=True)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pit_events', to='timing.teamsnapshot')),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('priority', models.IntegerField(default=1)),
                ('color', models.CharField(default='#00d4ff', max_length=7)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drivers', to='timing.racesession')),
            ],
            options={
                'ordering': ['priority'],
            },
        ),
        migrations.CreateModel(
            name='LapRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lap_number', models.IntegerField()),
                ('lap_time_seconds', models.FloatField()),
                ('sector1', models.FloatField(blank=True, null=True)),
                ('sector2', models.FloatField(blank=True, null=True)),
                ('sector3', models.FloatField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laps', to='timing.teamsnapshot')),
            ],
            options={
                'ordering': ['lap_number'],
                'unique_together': {('team', 'lap_number')},
            },
        ),
    ]
